title: "Documentation IFSI 1ʳᵉ année"
description: "Synthèses, fiches et cartes mentales par UE - Étudiante IFSI 2025"
theme: just-the-docs

url: "https://alifsicrip.github.io"
baseurl: "/lessons"

nav_sort: case_sensitive

aux_links:
  "Voir sur GitHub":
    - "https://github.com/alifsicrip/lessons"

search_enabled: true

collections:
  ue1:
    output: true
    permalink: /ue1/:path/
  ue2:
    output: true
    permalink: /ue2/:path/

color_scheme: light
