title: "Lessons IFSI 2025"
description: "Synthèses, fiches et cartes mentales de ma première année en soins infirmiers"
remote_theme: just-the-docs/just-the-docs
just_the_docs:
  search_enabled: true
plugins:
  - jekyll-include-cache
markdown: kramdown
